export const GET_ERRORS = "GET_ERRORS";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const GET_MATERIAL = "GET_MATERIAL";
export const MATERIAL_LOADING = "MATERIAL_LOADING";
export const CLEAR_CURRENT_MATERIAL = "CLEAR_CURRENT_MATERIAL";
